### ISSUE TITLE
db.phpを読み込むとWarning出まくる

### ISSUE THREAD

**Issue by Goryudyuma** [kstm-su/syllabus#2]
require_once(dirname(**FILE**).'/config.php');
がないせいだと思われる。

**Comment by bgpat** [comment]
`config.php`は`util.php`の中で`db.php`と一緒に`require_once`しています。
`util.php`のみを`require_once`すればいい構成となっています。

**Comment by Goryudyuma** [comment]
util.phpが必要になったのね、了解です。
